### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by almighty059** [matt8707/card-mod-helper#2]
@matt8707 I've tried to use your card-mod-helper and I just can't get it. Nothing seems to come out in a way that I could carry over the correct syntax to HA. I could find the element that I am trying to style by using the Dev Tools but after that, I'm lost. Have you ever made a video tutorial or any type of tutorial that could help me? I feel like if I'm shown one time how to interpret the code I'd be able to do it but whenever someone asks in the forums they usually get the answer instead of an explanation of how to get the answer which I think would be a lot better. Thanks and I apologize for opening an issue but I don't know another way to ask.

**Comment by matt8707** [comment]
Have you read all pages? https://github.com/thomasloven/lovelace-card-mod/wiki

This is important to understand https://github.com/thomasloven/lovelace-card-mod/wiki/Card-mod-Themes#special-theme-variables

Post your js path and I'll try to explain.

**Comment by almighty059** [comment]
@matt8707 yes I read all of that but I just realized something. At the top of the card-mod-helper page, it says that the tool "is for figuring out card-mod element selectors for **themes**" and the link you posted was for themes and using card-mod-<thing> and card-mod-<thing>-yaml with view, root and more-info. My issue is with the styling of individual lovelace cards which I don't think uses that does it.? 

My issue is taking what I see in the browsers element inspector and configuring it correcttly within the style element of an individual lovelace card. I understand the basic styling but I'm getting confused when it comes to shadow-DOM. Your tool helps with the js path from the browser element inspector which is needed for both styling themes and for styling individual lovelace cards correct.?  

The part of the card-mod 3 page that I keep going over is the DOM Navigation section. 
Link .> [https://github.com/thomasloven/lovelace-card-mod#dom-navigation](url)

I'm slowly getting it but my problem is when the element (i think I'm using the right word) is in a `shadow-root` and then inside another, another, etc. I get lost with when, where, and how to use `$` and `.` and indetting everything correctly which is why I was hoping your tool would help. If not, I'll keep working at it. 

Below is one of the js paths that I am struggling with. If it's too much to explain I totally understand and thank you for trying. 

```
document.querySelector("body > home-assistant").shadowRoot.querySelector("home-assistant-main").shadowRoot.querySelector("app-drawer-layout > partial-panel-resolver > ha-panel-lovelace").shadowRoot.querySelector("hui-root").shadowRoot.querySelector("#view > hui-view > grid-layout").shadowRoot.querySelector("#root > hui-conditional-card:nth-child(3) > hui-horizontal-stack-card").shadowRoot.querySelector("#root > stack-in-card:nth-child(2)").shadowRoot.querySelector("ha-card > div > hui-vertical-stack-card").shadowRoot.querySelector("#root > stack-in-card").shadowRoot.querySelector("ha-card > div > hui-horizontal-stack-card").shadowRoot.querySelector("#root > text-action-element").shadowRoot.querySelector("div")
```

**Comment by matt8707** [comment]
I see, it's all the same. If it's just a card you ignore all the cards before it.

I'm unsure what `text-action-element` is... I'm guessing https://github.com/custom-cards/text-action-element

It's supposed to go inside picture-elements. You're already in that shadow root so nothing hard here

`hui-picture-elements-card $ #root > text-action-element $ div`

```yaml
type: picture-elements
elements:
  - type: custom:text-action-element
    text: TEST
    card_mod:
      style: |
        div {
          color: red;
          background: yellow;
        }
```

---

But according to your path you're putting it outside of picture-elements? card-mod doesn't work here, probably because of unsupported usage, so you have to style from the card before it. A "shortcut" is to wrap it in mod-card.

`hui-horizontal-stack-card $ #root > text-action-element $ div`

```yaml
- type: custom:mod-card
  card_mod:
    style:
      text-action-element$: |
        div {
          color: red;
          background: yellow;
        }
  card:
    type: custom:text-action-element
    text: TEST
```

**Comment by almighty059** [comment]
@matt8707 thanks for the help. I actually redid that portion of code because a new HACS card made what I was doing a lot easier to do. I've actually been getting a better understanding of the syntax needed to style correctly. I also think I understand how to use mod-card because I've done it when I style a grid-card. I appreciate the help. Thanks again.
