### ISSUE TITLE
Browser Mod 2.0 breaks card-mod-helper?

### ISSUE THREAD

**Issue by CDRX2** [matt8707/card-mod-helper#3]
First of all, thank you very much for this tool. It has helped me navigate my way through CSS countless times.

It seems that the very recent update of browser mod 2.0 somehow messes with the card-mod-helper to output the selector.

For instance, I have many popups defined around my dashboard. I'd like to style a specific element, but when I copy the JS path, input it into card-mod-helper, the result is "Invalid JS path".

Screenshot:
![image](https://user-images.githubusercontent.com/35002821/188333981-2465f966-e45b-49aa-8506-67c92597b4ed.png)
I'd like to add `margin-bottom: -24px;` to `.content` in this `stack-in-card` shown in the popup.

The JS path for the stack-in-card highlighted in the screenshot is `document.querySelector("body > browser-mod-popup").shadowRoot.querySelector("ha-dialog > div.content > stack-in-card").shadowRoot.querySelector("ha-card")`.
This results in the Invalid JS path error message.

Have I missed something? Or is this due to the complete rewrite of browser mod?

**Comment by matt8707** [comment]
Hi, yes rewrite https://github.com/matt8707/hass-config/releases/tag/2022.9

I've updated https://matt8707.github.io/card-mod-helper/ so it's usable with browser-mod-popup

**Comment by CDRX2** [comment]
Amazing, works like a charm! Thank you very much!
